import "./PrivacyPolicyMobile.scss";
import { useSelector } from "react-redux";

const PrivacyPolicyMobile = () => {
  const darkMode = useSelector((state) => state.darkMode); // RESPONSIBLE FOR WEBSITE COLORS - DARK OR BRIGHT WEBSITE, BY DEFAULT IS BRIGHT
  const languagePrimary = useSelector((state) => state.languagePrimary); // RESPONSIBLE FOR WEBSITE LANGUAGE - ENGLISH OR POLISH
  return (
    <section className={darkMode ? "privacyPolicyMobile privacyPolicyMobile--styling privacyPolicyMobile--dark" : "privacyPolicyMobile privacyPolicyMobile--styling privacyPolicyMobile--bright"}>
      <div className="privacyPolicyMobile__container">
        <h1 className="container__header">{languagePrimary ? "Polityka RODO" : "Privacy Policy"}</h1>
        <p className="container__paragraph">
          Vivamus ac massa dolor. Proin iaculis est et mollis mattis. Sed in sodales nisl, vitae tempus nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam ut arcu lacus. Phasellus convallis vitae augue eu porta. Vestibulum luctus sapien odio, ut semper massa blandit nec. Pellentesque tempus ipsum eget tempor egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ac metus id ipsum varius
          imperdiet sit amet ac leo. Proin tempor tincidunt tortor vitae efficitur. Nam non eros nibh. Nunc placerat rutrum dolor, at aliquam quam consequat eget. Sed pulvinar odio nec lacus molestie molestie. Vivamus et metus in mi vulputate ornare. In hac habitasse platea dictumst.Duis lorem lectus, aliquet nec nisi sed, egestas porttitor nisl. Sed ac dolor pellentesque, sagittis purus eget, efficitur turpis. Aliquam consequat nunc vitae est hendrerit, eu mollis dui venenatis. Sed mattis quam
          sed est mollis sodales. Nam eu sagittis risus. Pellentesque mattis auctor diam convallis euismod. Mauris non lacus sed orci euismod suscipit. Morbi vel quam eget dolor volutpat scelerisque. Cras interdum faucibus turpis, mollis ultricies nisi eleifend non. Vestibulum id lacus nulla. Nulla facilisi.
        </p>
        <p className="container__paragraph">
          Aenean efficitur, eros id dignissim dictum, nulla erat condimentum nulla, et dapibus augue mauris nec turpis. Sed hendrerit odio id ornare tincidunt. Sed suscipit consequat tincidunt. Vivamus suscipit velit sed justo sodales, vulputate ullamcorper risus blandit. Aenean vestibulum erat non venenatis fringilla. Suspendisse finibus tempus tortor vitae ultricies. Cras ultrices dictum sagittis. Sed consequat odio urna, a pulvinar massa pulvinar et. Suspendisse a dui cursus, pharetra neque
          vel, iaculis massa. Nam finibus metus eu consectetur dignissim. Sed non sapien a lorem lobortis condimentum. In enim felis, volutpat a finibus a, tristique vel sem. Pellentesque suscipit, augue vitae placerat blandit, sapien nisl consectetur purus, non congue dui purus a elit. Aliquam erat volutpat. Fusce consequat volutpat quam, eget venenatis orci varius non. Sed ac felis lectus. Aliquam placerat, tortor a venenatis euismod, elit diam varius nunc, ultricies pellentesque sapien leo
          vel eros. Quisque aliquam suscipit diam, vitae ullamcorper augue pharetra a. Vestibulum consectetur pellentesque augue eget mollis. Etiam rutrum tortor et scelerisque semper. Duis hendrerit libero elit, id commodo lectus blandit id. Phasellus et nisl vel erat consequat faucibus et sit amet neque. Nunc dictum aliquet cursus. Nulla vitae ullamcorper enim, ut finibus lectus. Proin dui justo, sodales eget tellus vitae, aliquam dignissim neque. Vestibulum pulvinar tempor elit.
        </p>
        <p className="container__paragraph">
          Donec in elit iaculis, pulvinar sem vehicula, volutpat nunc. Donec vel faucibus enim. Nulla laoreet magna non vestibulum ultricies. Nulla facilisi. In hac habitasse platea dictumst. Phasellus fermentum ex et ex accumsan, vitae porttitor purus porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut viverra tortor et libero bibendum feugiat. Phasellus lectus mauris, hendrerit eget nisl in, molestie scelerisque ligula. Nulla vulputate
          dictum tortor eget pellentesque. Ut sit amet ante ante. Quisque posuere placerat enim, vel molestie augue tempor eget. Etiam dictum, arcu nec finibus viverra, lectus tortor posuere justo, in mattis ex sem ac enim. Sed feugiat ante sed dolor malesuada iaculis. Donec metus metus, egestas ac arcu sed, pretium bibendum nulla. Aliquam faucibus sodales nunc at vulputate. Donec varius mi eu nunc vulputate, dictum porttitor tortor efficitur. Vivamus quis venenatis metus, vel convallis justo.
          Nullam eleifend sapien id risus ultricies, eget faucibus diam tempus. Duis ultrices malesuada ante, mollis iaculis ex ullamcorper in. Pellentesque tincidunt euismod velit quis bibendum. Proin sed est et tortor molestie sodales. Sed sollicitudin arcu nec feugiat rutrum. Sed id auctor nulla, ac mattis sapien. Aliquam leo libero, tempus quis fermentum convallis, semper a erat. Proin eu ultrices dui. Mauris pellentesque sapien leo, eu facilisis erat rutrum nec. Vestibulum non elit nulla.
        </p>
        <p className="container__paragraph">
          Nam non tincidunt lorem. In et ante ac nulla gravida iaculis. Ut ac orci nunc. Fusce enim sem, malesuada in mi sit amet, eleifend sollicitudin turpis. Nulla volutpat dapibus semper. Nam vel suscipit odio. Nullam vel ex neque. Mauris ac risus quam. Integer ornare felis sed mattis pulvinar. Donec viverra sodales enim eu tincidunt. Suspendisse ut ipsum velit. Sed quis scelerisque tellus. Morbi risus magna, tincidunt sed dapibus vel, ullamcorper sed ipsum. Lorem ipsum dolor sit amet,
          consectetur adipiscing elit. Proin aliquet elit ultrices euismod commodo. Curabitur id finibus diam. Ut facilisis leo sem, vitae efficitur ex volutpat ut. Ut ornare pellentesque nisi sed molestie. Nulla at nunc diam. Aliquam vel mi orci. Nulla facilisi. Fusce scelerisque aliquet odio quis lacinia. Nunc sit amet orci vitae turpis varius imperdiet vitae ac nulla.
        </p>
        <p className="container__paragraph">
          Aenean efficitur, eros id dignissim dictum, nulla erat condimentum nulla, et dapibus augue mauris nec turpis. Sed hendrerit odio id ornare tincidunt. Sed suscipit consequat tincidunt. Vivamus suscipit velit sed justo sodales, vulputate ullamcorper risus blandit. Aenean vestibulum erat non venenatis fringilla. Suspendisse finibus tempus tortor vitae ultricies. Cras ultrices dictum sagittis. Sed consequat odio urna, a pulvinar massa pulvinar et. Suspendisse a dui cursus, pharetra neque
          vel, iaculis massa. Nam finibus metus eu consectetur dignissim. Sed non sapien a lorem lobortis condimentum. In enim felis, volutpat a finibus a, tristique vel sem. Pellentesque suscipit, augue vitae placerat blandit, sapien nisl consectetur purus, non congue dui purus a elit. Aliquam erat volutpat. Fusce consequat volutpat quam, eget venenatis orci varius non. Sed ac felis lectus. Aliquam placerat, tortor a venenatis euismod, elit diam varius nunc, ultricies pellentesque sapien leo
          vel eros. Quisque aliquam suscipit diam, vitae ullamcorper augue pharetra a. Vestibulum consectetur pellentesque augue eget mollis. Etiam rutrum tortor et scelerisque semper. Duis hendrerit libero elit, id commodo lectus blandit id. Phasellus et nisl vel erat consequat faucibus et sit amet neque. Nunc dictum aliquet cursus. Nulla vitae ullamcorper enim, ut finibus lectus. Proin dui justo, sodales eget tellus vitae, aliquam dignissim neque. Vestibulum pulvinar tempor elit.
        </p>
        <p className="container__paragraph">
          Donec in elit iaculis, pulvinar sem vehicula, volutpat nunc. Donec vel faucibus enim. Nulla laoreet magna non vestibulum ultricies. Nulla facilisi. In hac habitasse platea dictumst. Phasellus fermentum ex et ex accumsan, vitae porttitor purus porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut viverra tortor et libero bibendum feugiat. Phasellus lectus mauris, hendrerit eget nisl in, molestie scelerisque ligula. Nulla vulputate
          dictum tortor eget pellentesque. Ut sit amet ante ante. Quisque posuere placerat enim, vel molestie augue tempor eget. Etiam dictum, arcu nec finibus viverra, lectus tortor posuere justo, in mattis ex sem ac enim. Sed feugiat ante sed dolor malesuada iaculis. Donec metus metus, egestas ac arcu sed, pretium bibendum nulla. Aliquam faucibus sodales nunc at vulputate. Donec varius mi eu nunc vulputate, dictum porttitor tortor efficitur. Vivamus quis venenatis metus, vel convallis justo.
          Nullam eleifend sapien id risus ultricies, eget faucibus diam tempus. Duis ultrices malesuada ante, mollis iaculis ex ullamcorper in. Pellentesque tincidunt euismod velit quis bibendum. Proin sed est et tortor molestie sodales. Sed sollicitudin arcu nec feugiat rutrum. Sed id auctor nulla, ac mattis sapien. Aliquam leo libero, tempus quis fermentum convallis, semper a erat. Proin eu ultrices dui. Mauris pellentesque sapien leo, eu facilisis erat rutrum nec. Vestibulum non elit nulla.
        </p>
      </div>
    </section>
  );
};

export default PrivacyPolicyMobile;
